### ISSUE TITLE
Star and Starburst are rendering badly...

### ISSUE THREAD

**Issue by MishkinBerteig** [spacedeck/spacedeck-open#78]
First of all, the selection bounding box doesn't touch the tips of the stars' points.  Also, with large stroke-widths, the points go beyond the bounding box and are therefore cut off.

I have fixed this with the judicious application of a bit of math.  I'm new to contributing to open source... how can I contribute my fixes?

Here is a page where I have [illustrated the problem and my fixes](http://www.mishkinberteig.com/open-source-project-spacedeck/).

**Comment by MishkinBerteig** [comment]
Submitted a pull request.  Figured all that out.

**Comment by yrammos** [comment]
@MishkinBerteig thanks for an excellent PR. Along similar lines, I noticed that the pen (scribble) tool works incorrectly with line lengths below a certain threshold (more specifically, the tip of the pen does not follow the ink trace). The problem is aggravated with the view zoomed in above the 150%-200% range. I'm planning to look into the issue whenever time permits, but if you happen to have a solution earlier, do not hesitate to share...

**Comment by MishkinBerteig** [comment]
Thanks @yrammos .  It was an easy problem to fix. I am happy to look at the scribble problem, but that likely won’t happen until next week. My contributions will be spread out between work and family stuff! Still, I hope to make Spacedeck good enough for production use with my clients.
